openapi: 3.0.0
info:
  title: Example MCP Calculator API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Healthy response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /calculate:
    post:
      summary: Perform calculator operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operation:
                  type: string
                  enum: [add, subtract, multiply, divide]
                a:
                  type: number
                b:
                  type: number
      responses:
        '200':
          description: Calculation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  operation:
                    type: string
                  a:
                    type: number
                  b:
                    type: number
                  result:
                    type: number
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
