# Gemini CLI Base Configuration ( ~/.gemini/config.yaml )

default_model: gemini-1.5-flash-latest

generation_config:
  temperature: 0.9

safety_settings:
  harassment: BLOCK_MEDIUM_AND_ABOVE
  hate_speech: BLOCK_MEDIUM_AND_ABOVE
  sexually_explicit: BLOCK_MEDIUM_AND_ABOVE
  dangerous_content: BLOCK_MEDIUM_AND_ABOVE

tools:
  web_search: true
  file_system: true
  shell: true
  memory: true
  mcp_server: true

telemetry:
  enabled: true # Set to false to disable
  # endpoint: <custom_endpoint_if_needed> # Optional: Specify a custom telemetry endpoint URL

ui:
  theme: default

check_for_updates: true
