# Gemini CLI Profiles ( ~/.gemini/profiles.yaml )
coder:
  description: "Profile optimized for coding tasks"
  default_model: gemini-1.5-pro-latest
  generation_config:
    temperature: 0.5
writer:
  description: "Profile optimized for creative writing"
  default_model: gemini-1.5-flash-latest
  generation_config:
    temperature: 1.0
  tools:
    web_search: true
